### PR TITLE
Initial commit.

### PR DESCRIPTION
**Pull request by nkinkade**
This PR introduces 3 small packages: main, snmp and config, along with their unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/disco/1)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Please add automated unit tests and simple code coverage, like https://github.com/m-lab/locate/blob/master/.travis.yml

TIP: if you enable the repo in travis before you push the config it will run the first time. Same for coveralls.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1#-:-M9tlgnD7DYijSzPnzfS:b-hjqpnz)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmFDXB52r6OHAb6VJ:-M9tmFDXB52r6OHAb6VK:b7ee4if) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:alpine as disco-build
> ```

Is it possible to use a versioned tag? The resulting image could change from one build to the next without a specific version. One of the principles we were close to formalizing from the ops-tactical is explicit versions. I think the same principle applies here.
___
*[disco.go, line 20 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tnHU0B6t4rlZwFLLW:-M9tnHU0B6t4rlZwFLLX:bkyvo1g) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L20)):*
> ```Go
> 
> var (
> 	community           = os.Getenv("DISCO_COMMUNITY")
> ```

Is it possible to use `flagx.ArgsFromEnv` instead? then this value could be either a flag or from the env. Plus it can be documented in the help text automatically.

I would also recommend this because this will be a daemon process.
___
*[disco.go, line 36 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tpoMlD8ILMsdGZ9eJ:-M9tpoMlD8ILMsdGZ9eK:b-aijd25) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L36)):*
> ```Go
> 	}
> 
> 	hostname, err := os.Hostname()
> ```

What value does this return? Within a pod, the `hostname` command returns the pod name, e.g.

```
/ # hostname
ndt-jls42
```

I suggest that we get this from k8s as the `$(NODE_NAME)` (or similar) environment variable (or flag)
___
*[disco.go, line 44 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tqMFK9VwatYWZrj1j:-M9tqMFK9VwatYWZrj1k:bvix3q) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L44)):*
> ```Go
> 		Community: community,
> 		Version:   gosnmp.Version2c,
> 		Timeout:   time.Duration(2) * time.Second,
> ```

What does this timeout apply to? Is this long enough?
___
*[disco.go, line 56 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trqzU-hLEoEBsuuLP:-M9trqzU-hLEoEBsuuLQ:b-tex8v5) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L56)):*
> ```Go
> 
> 	// Start scraping on a clean 10s boundary within a minute.
> 	for time.Now().Second()%10 != 0 {
> ```

Does the cron run every "interval" from the time `Do` is called?
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmeXT-INEUkZOxX9I:-M9tmeXT-INEUkZOxX9J:b4xm6vv) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/README.md#L2)):*
> ```Markdown
> # DISCOv2
> DISCOv2 is a reimplementation of the DISCO parts of
> ```

VScode has a great Markdown linter "markdownlint". I suggest installing it. For example here it would complain that there should be whitespace between the heading and paragraph. There are several other places that it would suggest extra whitespace.
___
*[README.md, line 11 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmnEj4-gTQ1JD-WYz:-M9tmnEj4-gTQ1JD-WZ-:b-pefcbn) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/README.md#L11)):*
> ```Markdown
> DISCOv2 supports the following flags:
> * `--prometheusx.listen-address`: the IP and TCP port to listen to for Prometheus metricis requests.
> * `--metrics-file`: the path to a YAML-formatted file defining which metrics to scrape. See file metrics.yaml in this repo for an example.
> ```

nit: Do your best to wrap these long lines around 80cols.

The goal is to make the file as easy to read in it's raw MD form as it is to read in the generated html form.
___
*[config/config_test.go, line 63 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tuseX3y7F2jhM3Q0v:-M9tuseX3y7F2jhM3Q0w:b7iy1ig) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/config/config_test.go#L63)):*
> ```Go
> 
> 	c, err := New(dir + "/metrics.yaml")
> ```

nit: remove extra new line.
___
*[config/config_test.go, line 70 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tuvnd3r4uUdOigX3x:-M9tuvnd3r4uUdOigX3y:b7iy1ig) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/config/config_test.go#L70)):*
> ```Go
> 
> 	m := c.Metrics[0]
> ```

nit: remove extra new line.
___
*[snmp/snmp.go, line 14 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trLgn5WFtu4L9CFwx:-M9trLgn5WFtu4L9CFwy:b93hed1) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/snmp/snmp.go#L14)):*
> ```Go
> 
> // RealSNMP implements the SNMP interface.
> type RealSNMP struct {
> ```

I suggest naming this type `Client`.
___
*[snmp/snmp.go, line 30 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trRffCPdgXRN-Wk20:-M9trRfgBZg7JwbvHtRM:b-91j6cw) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/snmp/snmp.go#L30)):*
> ```Go
> 
> // Client returns a new RealSNMP object.
> func Client(s *gosnmp.GoSNMP) *RealSNMP {
> ```

I suggest naming this function `New` or `NewClient`.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmFDXB52r6OHAb6VJ:-M9u0OjQB8SBsvPrwkui:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/Dockerfile#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to use a versioned tag? The resulting image could change from one build to the next without a specific version. One of the principles we were close to formalizing from the ops-tactical is explicit versions. I think the same principle applies here.
</blockquote></details>

Done.
___
*[disco.go, line 20 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tnHU0B6t4rlZwFLLW:-M9u4Yw_C7FkU-LFJBgj:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to use `flagx.ArgsFromEnv` instead? then this value could be either a flag or from the env. Plus it can be documented in the help text automatically.

I would also recommend this because this will be a daemon process.
</blockquote></details>

Done.
___
*[disco.go, line 36 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tpoMlD8ILMsdGZ9eJ:-M9u6-xqDxQIBlE5wGo9:b-eh0q71) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What value does this return? Within a pod, the `hostname` command returns the pod name, e.g.

```
/ # hostname
ndt-jls42
```

I suggest that we get this from k8s as the `$(NODE_NAME)` (or similar) environment variable (or flag)
</blockquote></details>

Done. Thank you for catching this, which would have been a problem in k8s. Additionally, this makes testing much easier. Before, every time I needed to test this locally, I had to comment out the  code and hard code the hostname, then remember to undo that before making any commits etc.
___
*[disco.go, line 44 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tqMFK9VwatYWZrj1j:-M9u6wFv7iu-UKa56OPS:b-pj7gk8) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L44)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What does this timeout apply to? Is this long enough?
</blockquote></details>

It's the timeout for any given SNMP query. I had set it to 2 with the expectation that on the local network queries would complete almost always in less than 1s, and to keep it low since the scrape interval is 10s. I've upped it to 5s, which seems reasonable.
___
*[disco.go, line 56 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trqzU-hLEoEBsuuLP:-M9u7QFl8OaLzIhLjrZ1:bdo8jb2) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the cron run every "interval" from the time `Do` is called?
</blockquote></details>

My understanding is that it will wait <interval> to begin once `Do()` is called, unless `StartImmediately()` is specified.  I specify `StartImmediately()` for `Collect()`, but I don't for `Write()`.
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmeXT-INEUkZOxX9I:-M9u8Nuu9xuVsG0VSEOs:bt4ox1i) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

VScode has a great Markdown linter "markdownlint". I suggest installing it. For example here it would complain that there should be whitespace between the heading and paragraph. There are several other places that it would suggest extra whitespace.
</blockquote></details>

Done. Thanks for the suggestion.
___
*[README.md, line 11 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmnEj4-gTQ1JD-WYz:-M9u8iy27iHpAsYsKPWi:bblp91j) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/README.md#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: Do your best to wrap these long lines around 80cols.

The goal is to make the file as easy to read in it's raw MD form as it is to read in the generated html form.
</blockquote></details>

Done. But why 80cols? I've been super excited that Go doesn't place that style guideline like so many other languages, or is at least more relaxed about it. Virtually nobody is looking at file in an 80col console these days. Even relatively small terminals are generally wider than 80cols.
___
*[config/config_test.go, line 63 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tuseX3y7F2jhM3Q0v:-M9u9Ob83WWjCqMRt754:b-3u9spq) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/config/config_test.go#L63)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: remove extra new line.
</blockquote></details>

Done. I'm assuming you mean only the newline below the assignment and not also the line above the assignment.
___
*[config/config_test.go, line 70 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tuvnd3r4uUdOigX3x:-M9u9Zf_4Kcl5URmEEzb:b-3u9spq) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/config/config_test.go#L70)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: remove extra new line.
</blockquote></details>

Done. I'm assuming you mean only the newline below the assignment and not also the line above the assignment.
___
*[snmp/snmp.go, line 14 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trLgn5WFtu4L9CFwx:-M9uAefU92JLsiG5Z94k:b-lf5see) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/snmp/snmp.go#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest naming this type `Client`.
</blockquote></details>

Done. This is a much better name.
___
*[snmp/snmp.go, line 30 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9trRffCPdgXRN-Wk20:-M9uAhVf3jLvY4bTMPgx:bzcuv85) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/snmp/snmp.go#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest naming this function `New` or `NewClient`.
</blockquote></details>

Done. Change to just `New()`.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 4 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[disco.go, line 44 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tqMFK9VwatYWZrj1j:-M9xBRx8DpYtFjLabz3S:b-804xm3) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/disco.go#L44)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It's the timeout for any given SNMP query. I had set it to 2 with the expectation that on the local network queries would complete almost always in less than 1s, and to keep it low since the scrape interval is 10s. I've upped it to 5s, which seems reasonable.
</blockquote></details>

:+1: yeah, 5s with one retry should fit within the window. Also, this reminds me of the value of having the additional timestamps collected so we can observe the error.
___
*[disco.go, line 15 at r2](https://reviewable.io/reviews/m-lab/disco/1#-M9xCxOTBBdZ-7VzQWqH:-M9xCxOTBBdZ-7VzQWqI:b-k88thx) ([raw file](https://github.com/m-lab/disco/blob/adfb2ae551028ec2ff445f1b8867e34e448e8df6/disco.go#L15)):*
> ```Go
> 	"github.com/m-lab/go/prometheusx"
> 	"github.com/m-lab/go/rtx"
> 	"github.com/nkinkade/disco-go/metrics"
> ```

nkinkade?

I strongly advise to only create PRs with working builds. In this case it might mean removing some files until their dependencies are satisfied.
___
*[README.md, line 11 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tmnEj4-gTQ1JD-WYz:-M9xBu27DjwnEPd9u-V6:bf744p7) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/README.md#L11)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. But why 80cols? I've been super excited that Go doesn't place that style guideline like so many other languages, or is at least more relaxed about it. Virtually nobody is looking at file in an 80col console these days. Even relatively small terminals are generally wider than 80cols.
</blockquote></details>

80 is still arbitrary. Less than infinite is mostly what I'm going for. Please keep it consistent and less than 100. 100 is equally arbitrary but it fits on my (and others) screens in reviewable with diffs.
___
*[config/config_test.go, line 63 at r1](https://reviewable.io/reviews/m-lab/disco/1#-M9tuseX3y7F2jhM3Q0v:-M9xCRrB2Rat-bH7wTbN:boavt38) ([raw file](https://github.com/m-lab/disco/blob/01849e1f61a5f198aaac1402e69126cbe15de3a9/config/config_test.go#L63)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. I'm assuming you mean only the newline below the assignment and not also the line above the assignment.
</blockquote></details>

Right just where this comment was.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[disco.go, line 15 at r2](https://reviewable.io/reviews/m-lab/disco/1#-M9xCxOTBBdZ-7VzQWqH:-M9xqJ9g5-jjXpRDSWQu:b-wdluci) ([raw file](https://github.com/m-lab/disco/blob/adfb2ae551028ec2ff445f1b8867e34e448e8df6/disco.go#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nkinkade?

I strongly advise to only create PRs with working builds. In this case it might mean removing some files until their dependencies are satisfied.
</blockquote></details>

Understood. I realized this was going to be a problem when submitting this PR but wasn't at the time sure how to avoid it. In retrospect, I see that `archive`, `config` and `snmp` have no interdependencies, but `main` and `metrics` do. I suppose I could have first sent you , say, `config`, `snmp` and `archive` (all pretty small), then `metrics`, then finally `main`. 

To be sure I understand, are you suggesting that  I remove `main`, `Dockerfile` and the parts of `cloudconfig.yaml` that try to build the Docker image from this PR.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[disco.go, line 15 at r2](https://reviewable.io/reviews/m-lab/disco/1#-M9xCxOTBBdZ-7VzQWqH:-M9xvuIX0rzpdERGjgC5:bh4oc0r) ([raw file](https://github.com/m-lab/disco/blob/adfb2ae551028ec2ff445f1b8867e34e448e8df6/disco.go#L15)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Understood. I realized this was going to be a problem when submitting this PR but wasn't at the time sure how to avoid it. In retrospect, I see that `archive`, `config` and `snmp` have no interdependencies, but `main` and `metrics` do. I suppose I could have first sent you , say, `config`, `snmp` and `archive` (all pretty small), then `metrics`, then finally `main`. 

To be sure I understand, are you suggesting that  I remove `main`, `Dockerfile` and the parts of `cloudconfig.yaml` that try to build the Docker image from this PR. 
</blockquote></details>

Okay, done, and the builds are now passing in both Cloud Build and Travis. I think everything is reviewed, especially since I've removed a file that was already reviews. PTAL?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- I suggest using "Squash and Merge" settings for the repo too.

> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/1#-:-M9xwYmyDEXXabPrb1of:bfqs6ab)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
