### PR TITLE
Catches SIGTERM and writes all data to disk before exiting.

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/disco/8)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[disco.go, line 109 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY45CfB7Ql0gRHWmKM:-MAY45CfB7Ql0gRHWmKN:bslb8um) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L109)):*
> ```Go
> 		case <-sigterm:
> 			start := metrics.IntervalStart
> 			metrics.IntervalStart = time.Now()
> ```

What is the significance of resetting the IntervalStart?
___
*[disco.go, line 111 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY4W4N3w34dh17TWMB:-MAY4MdE7QBid2dXiBLK:b-mn4kur) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L111)):*
> ```Go
> 			metrics.IntervalStart = time.Now()
> 			metrics.Write(start, time.Now(), *fDataDir)
> 			mainCancel()
> ```

Hmm, I think we want to guarantee that the process exits next. I don't think Go guarantees which select channel is selected if more than one are available. It could be possible for this branch to return to the `for` loop and any of the other case statements to run before `return`.

I think this could be solved by `defer` ing the collectTicker and writeTicker Stops before the for loop, and returning right away here.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[disco.go, line 109 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY45CfB7Ql0gRHWmKM:-MAY5YZJ2-hQcQf46iHV:b4zwnb5) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L109)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the significance of resetting the IntervalStart?
</blockquote></details>

Nothing. Just me copying all the contents of a the `Write()` ticker this location. Removed.
___
*[disco.go, line 111 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY4W4N3w34dh17TWMB:-MAY6NGu1y3azQnuvPRl:b3f0mb0) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L111)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I think we want to guarantee that the process exits next. I don't think Go guarantees which select channel is selected if more than one are available. It could be possible for this branch to return to the `for` loop and any of the other case statements to run before `return`.

I think this could be solved by `defer` ing the collectTicker and writeTicker Stops before the for loop, and returning right away here.
</blockquote></details>

Done, I believe.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - with one more change.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/8#-:-MAY6roYAJSpzoo8Ssdp:b-oyqlyz)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[disco.go, line 111 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY4W4N3w34dh17TWMB:-MAY6kUy-3A6EwfV_JE3:bwwusqe) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L111)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done, I believe.
</blockquote></details>

Please keep the `mainCancel()` -- this releases the goroutine above blocking on:

```
	go func() {
		<-mainCtx.Done()
		goSNMP.Conn.Close()
		promSrv.Close()
	}()

```

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/8)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[disco.go, line 111 at r1](https://reviewable.io/reviews/m-lab/disco/8#-MAY4W4N3w34dh17TWMB:-MAYA2aJ1XabratVINKy:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/03bdc2121bb72cdeeb41f6f5c09e035ff7e75a1d/disco.go#L111)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please keep the `mainCancel()` -- this releases the goroutine above blocking on:

```
	go func() {
		<-mainCtx.Done()
		goSNMP.Conn.Close()
		promSrv.Close()
	}()

```
</blockquote></details>

Done.

**Pull request merged**
