### PR TITLE
Fixes a typo of metric name for ifHCInOctets

### PR DESCRIPTION
**Pull request by nkinkade**
Resolves issue #20.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/disco/21)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21#-:-MrcxHIU8b2G94skMC8a:bnfp4nl)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[metrics.yaml, line 4 at r1](https://reviewable.io/reviews/m-lab/disco/21#-Mrcx2m--nfGDFJvOV1O:-Mrcx2m--nfGDFJvOV1P:b-mw1a11) ([raw file](https://github.com/m-lab/disco/blob/339f27f445a99ee203709c4a16f54a446202aba8/metrics.yaml#L4)):*
> ```YAML
>   description: Ingress octets.
>   oidStub: .1.3.6.1.2.1.31.1.1.1.6
>   mlabUplinkName: switch.octets.uplink.rx
> ```

How is `mlabUplinkName` used? if both of these labels were in the archive we might have a fall back.

**Review by stephen-soltesz — APPROVED** [review]
c

> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21#-:-MrcxKhCDMlqvS-TWhLP:b3kse)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: The build failed because of a lack of Go module support. I made an additional commit adding Go module support, and fixing any other things required for the change.  I also went ahead and bumped the Dockerfile build image to Go 1.16 and alpine 3.15.  PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21#-:-MrdDAYh1s8pqVa-MNop:b-i0eg1k)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics.yaml, line 4 at r1](https://reviewable.io/reviews/m-lab/disco/21#-Mrcx2m--nfGDFJvOV1O:-MrdCAOZ1GQX85jL1tWP:b2q6qqq) ([raw file](https://github.com/m-lab/disco/blob/339f27f445a99ee203709c4a16f54a446202aba8/metrics.yaml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How is `mlabUplinkName` used? if both of these labels were in the archive we might have a fall back.
</blockquote></details>

It describe the metric in our archive format for the named SNMP metric for the uplink port (as opposed to the machine's port). It is not associated in any way with the `mlabMachineName` value in the archives.  That is, you'll have something like:

```
{
  "experiment": "s1-bom02.measurement-lab.org",
  "hostname": "mlab1-bom02.mlab-oti.measurement-lab.org",
  "metric": "switch.octets.local.rx",
  "sample": [
    {
      "timestamp": 1640131210,
      "collectstart": 1640131210000917000,
      "collectend": 1640131210039261400,
      "value": 174448,
      "counter": 496819292699829
    }
}
{
  "experiment": "s1-bom02.measurement-lab.org",
  "hostname": "mlab1-bom02.mlab-oti.measurement-lab.org",
  "metric": "switch.octets.uplink.rx",
  "sample": [
    {
      "timestamp": 1640131210,
      "collectstart": 1640131210000917000,
      "collectend": 1640131210039261400,
      "value": 104181229,
      "counter": 1509502301580966
    }
}
```

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[metrics/metrics_test.go, line 408 at r4](https://reviewable.io/reviews/m-lab/disco/21#-MrdKHfeBbHEkFWg44lb:-MrdKHfeBbHEkFWg44lc:b-x4mhrq) ([raw file](https://github.com/m-lab/disco/blob/80c14a54192c2c2b8397e69d31fc3d6b1f1fd680/metrics/metrics_test.go#L408)):*
> ```Go
> 		t.Errorf("Expected one archive file, but got: %v", len(a))
> 	}
> 	os.RemoveAll(string(rune(time.Now().Year())))
> ```

This doesn't feel right. I don't think this works. I think this is closer to what python might do with: `chr(2021)`

Please use `fmt.Sprintf("%04d", time.Now().Year())` as the argument to `RemoveAll()`

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics_test.go, line 408 at r4](https://reviewable.io/reviews/m-lab/disco/21#-MrdKHfeBbHEkFWg44lb:-MrdMVuY2rJlOM1LP5Y7:b-76oee7) ([raw file](https://github.com/m-lab/disco/blob/80c14a54192c2c2b8397e69d31fc3d6b1f1fd680/metrics/metrics_test.go#L408)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This doesn't feel right. I don't think this works. I think this is closer to what python might do with: `chr(2021)`

Please use `fmt.Sprintf("%04d", time.Now().Year())` as the argument to `RemoveAll()`
</blockquote></details>

The error message emitted was:

```
conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

But when I was searching for the error, one of the first things I came across was this Prometheus issue:

https://github.com/prometheus/prometheus/issues/7706

... and the PR resulting from that issue just wrapped the int in `rune()`.  And the issue also references this:

https://github.com/golang/go/issues/32479

... which would seem to indicate that type conversion between `rune` and `string` is okay. 

But maybe `fmt.Sprintf()` is a better solution. I've made your requested change.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21#-:-MrdPD1t5HolS865-EYS:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics_test.go, line 408 at r4](https://reviewable.io/reviews/m-lab/disco/21#-MrdKHfeBbHEkFWg44lb:-MrdP4ug2nXjfQdDXY--:b-yh6vva) ([raw file](https://github.com/m-lab/disco/blob/80c14a54192c2c2b8397e69d31fc3d6b1f1fd680/metrics/metrics_test.go#L408)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The error message emitted was:

```
conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

But when I was searching for the error, one of the first things I came across was this Prometheus issue:

https://github.com/prometheus/prometheus/issues/7706

... and the PR resulting from that issue just wrapped the int in `rune()`.  And the issue also references this:

https://github.com/golang/go/issues/32479

... which would seem to indicate that type conversion between `rune` and `string` is okay. 

But maybe `fmt.Sprintf()` is a better solution. I've made your requested change.
</blockquote></details>

Thank you for the update.

Please see: https://go.dev/play/p/7_woGwxuiUD

What do you expect to happen? What is actually output?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/21)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics_test.go, line 408 at r4](https://reviewable.io/reviews/m-lab/disco/21#-MrdKHfeBbHEkFWg44lb:-MrdP_oa88vaLVExWgCB:b-rsppo0) ([raw file](https://github.com/m-lab/disco/blob/80c14a54192c2c2b8397e69d31fc3d6b1f1fd680/metrics/metrics_test.go#L408)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for the update.

Please see: https://go.dev/play/p/7_woGwxuiUD

What do you expect to happen? What is actually output?
</blockquote></details>

I stand corrected. Thank you for catching that bug!

**Pull request merged**
